services:
  de:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports: 
     - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /Users/viton/OneDrive/Área de Trabalho/Dev/Python/mysql:/var/lib/mysql